### ISSUE TITLE
Use new version of SDK

### ISSUE THREAD

**Issue by dusanb94** [mainflux/provision#3]
Once this issue is resolved (https://github.com/mainflux/mainflux/issues/862), we should switch to using SDK, rather than creating our workaround for consuming Bootstrap (and Certs) API.

**Comment by manuio** [comment]
@mteodor was this resolved here: https://github.com/mainflux/mainflux/pull/1133 ?
If yes can we close this one and maybe also remove the repo?

**Comment by mteodor** [comment]
yes it is resolved

**Comment by mteodor** [comment]
closing as resolved by https://github.com/mainflux/mainflux/pull/1133
